M48
; DRILL file {KiCad (6.0.0)} date Sat Nov 26 21:53:33 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-26T21:53:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0374
%
G90
G05
T1
X4.5457Y-3.626
T2
X4.5457Y-3.9094
T0
M30
